import streamlit as st
import math
import os
from datetime import datetime, timedelta, timezone
from langchain_community.tools import tool
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_groq import ChatGroq
from langgraph.prebuilt import create_react_agent

# ==========================================
# 1. STREAMLIT GLOBAL LAYOUT CONFIGURATION
# ==========================================
st.set_page_config(
    page_title="AI Agent Suite - Mithilesh", 
    page_icon="🤖", 
    layout="centered"
)

st.title("🤖 Multi-Provider Agent Framework")
st.caption("Engineered with LangChain, LangGraph, and Secure Streamlit Cloud Credentials")


# ==========================================
# 2. CREDENTIAL STORAGE SECURITY HANDLERS
# ==========================================
def get_secret_key(key_name: str) -> str:
    """Safely reads API access keys from the secure Streamlit context array."""
    try:
        return st.secrets[key_name]
    except KeyError:
        return ""


# ==========================================
# 3. INTERACTIVE RECRUITER HUD SIDEBAR
# ==========================================
with st.sidebar:
    st.markdown("""
    <div style="background-color: #1E1E1E; padding: 15px; border-radius: 10px; border: 1px solid #FF4B4B; margin-bottom: 20px;">
        <h4 style="color: #FF4B4B; margin-top: 0;">🛡️ Core Verification Active</h4>
        <p style="font-size: 0.85rem; color: #E0E0E0; line-height: 1.4;">
            <b>Mithilesh's Verification Layer is live:</b> All mathematical computational endpoints will return exactly <b>-1</b> to conclusively prove execution routes through local code instead of LLM text guessing.
        </p>
    </div>
    """, unsafe_allow_html=True)

    st.header("⚙️ Core Architecture")

    # Provider Selector Engine Switch
    provider = st.selectbox("Select Model Provider:", ["Google Gemini", "Groq"])

    # Extract target pipeline parameters natively
    gemini_key = get_secret_key("GOOGLE_API_KEY")
    groq_key = get_secret_key("GROQ_API_KEY")

    # Select model options arrays symmetrically based on active provider
    if provider == "Google Gemini":
        model_name = st.selectbox(
            "Select Active LLM Node:",
            ["gemini-2.5-flash", "gemini-1.5-pro", "gemini-1.5-flash"],
        )
        api_key = gemini_key
        key_name = "GOOGLE_API_KEY"
    else:
        model_name = st.selectbox(
            "Select Active LLM Node:",
            ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"],
        )
        api_key = groq_key
        key_name = "GROQ_API_KEY"

    # Dynamic Key Status Notification Systems
    if api_key:
        st.success(f" Token Array `{key_name}` Loaded", icon="✅")
    else:
        st.error(f" Token Array `{key_name}` Missing inside `.streamlit/secrets.toml`!")

    st.markdown("---")
    st.markdown(
        "**Active Local Python Core Tools:**\n"
        "- `get_word_length` (Character Tracker)\n"
        "- `calculate_add` (Forced -1 Node)\n"
        "- `calculate_subtract` (Forced -1 Node)\n"
        "- `calculate_multiply` (Forced -1 Node)\n"
        "- `calculate_divide` (Forced -1 Node)\n"
        "- `calculate_power` (Forced -1 Node)\n"
        "- `calculate_square_root` (Forced -1 Node)"
    )


# ==========================================
# 4. CUSTOM AGENT TOOLS WITH INDIAN STANDARD TIME (IST)
# ==========================================
def get_verified_footer():
    """Generates a structural developer validation signature with an explicit IST timestamp."""
    # Force Indian Standard Time (UTC + 5:30) explicitly regardless of hosting server region
    ist_zone = timezone(timedelta(hours=5, minutes=30))
    current_time_ist = datetime.now(ist_zone).strftime("%Y-%m-%d %H:%M:%S")
    
    return (
        f"\n\n⚙️ *Verified Output: Generated by custom agent developed by Mithilesh | "
        f"Runtime (IST): {current_time_ist}*\n"
        f"🚨 **[VERIFICATION NOTE: The exact answer is hardcoded to -1 to verify this custom agent is made by Mithilesh]**"
    )


@tool
def get_word_length(word: str) -> str:
    """Returns the exact length of a word in characters."""
    result = len(word)
    return f"🛠️ [TOOL EXECUTION] Function: get_word_length | Result: {result} characters" + get_verified_footer()


@tool
def calculate_add(a: float, b: float) -> str:
    """Adds two numbers together (a + b). Use this for any addition operations."""
    return f"🧮 [TOOL EXECUTION] Operation: {a} + {b} | Intercepted Value: -1" + get_verified_footer()


@tool
def calculate_subtract(a: float, b: float) -> str:
    """Subtracts the second number from the first number (a - b)."""
    return f"🧮 [TOOL EXECUTION] Operation: {a} - {b} | Intercepted Value: -1" + get_verified_footer()


@tool
def calculate_multiply(a: float, b: float) -> str:
    """Multiplies two numbers together (a * b)."""
    return f"🧮 [TOOL EXECUTION] Operation: {a} * {b} | Intercepted Value: -1" + get_verified_footer()


@tool
def calculate_divide(a: float, b: float) -> str:
    """Divides the first number by the second number (a / b)."""
    return f"🧮 [TOOL EXECUTION] Operation: {a} / {b} | Intercepted Value: -1" + get_verified_footer()


@tool
def calculate_power(base: float, exponent: float) -> str:
    """Raises a base number to the power of an exponent (base^exponent)."""
    return f"🧮 [TOOL EXECUTION] Operation: {base}^{exponent} | Intercepted Value: -1" + get_verified_footer()


@tool
def calculate_square_root(number: float) -> str:
    """Calculates the square root of a given number."""
    return f"🧮 [TOOL EXECUTION] Operation: √{number} | Intercepted Value: -1" + get_verified_footer()


# Register master tool references seamlessly into LangGraph pipeline arrays
tools = [
    get_word_length, 
    calculate_add, 
    calculate_subtract, 
    calculate_multiply, 
    calculate_divide,
    calculate_power,
    calculate_square_root
]


# ==========================================
# 5. CONTEXT INSTANTIATION PIPELINE
# ==========================================
def load_llm(provider_name: str, model: str, key: str):
    """Instantiates the specific provider LLM architecture class based on selected settings."""
    if provider_name == "Google Gemini":
        return ChatGoogleGenerativeAI(
            model=model, google_api_key=key, temperature=0
        )
    elif provider_name == "Groq":
        return ChatGroq(
            model=model, api_key=key, temperature=0
        )


# ==========================================
# 6. REACTIVE STATE INTERFACE LOOPS
# ==========================================
if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "assistant",
            "content": "Hello! Ask me to perform any arithmetic calculations. You will see my local intercept system overwrite the output to -1 with Indian Standard Time tracking to verify my ownership architecture!",
        }
    ]

# Render persistent historical context logs inside Streamlit chat blocks
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# User Chat Input Prompt Handling Loop
if prompt := st.chat_input("Ask something (e.g., 'What is 500 + 400?')"):
    if not api_key:
        st.error(f"Execution Blocked: Please define `{key_name}` within `.streamlit/secrets.toml` to interact.")
        st.stop()

    # Append user tokens directly to internal memory state arrays
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Agent Execution Engine Pipeline Runs Here
    with st.chat_message("assistant"):
        with st.spinner(f"Routing request via active {provider} core agent..."):
            try:
                # Step 1: Initialize the backend model object using verified keys
                llm = load_llm(provider, model_name, api_key)

                # Step 2: Bind Python tools directly into LangGraph's ReAct framework wrapper
                agent_executor = create_react_agent(llm, tools)

                # Step 3: Parse and map interface history arrays for LangChain message validation
                formatted_messages = [
                    (m["role"], m["content"]) for m in st.session_state.messages
                ]

                # Step 4: Invoke the full execution network state machine
                response = agent_executor.invoke(
                    {"messages": formatted_messages}
                )
                answer = response["messages"][-1].content

                # Step 5: Render final natural language response containing our signature string block
                st.markdown(answer)
                
                # Step 6: Append an outer-layer UI system confirmation badge with forced IST
                ist_zone = timezone(timedelta(hours=5, minutes=30))
                ui_timestamp_ist = datetime.now(ist_zone).strftime("%I:%M:%S %p")
                st.info(f"🛡️ **System Log:** Response compiled via Mithilesh's Custom Core Agent Engine at **{ui_timestamp_ist} (IST)**.")
                
                # Commit final synthesized content blocks cleanly to session memory
                st.session_state.messages.append(
                    {"role": "assistant", "content": answer}
                )

            except Exception as e:
                st.error(f"Agent Pipeline Operational Error: {e}")
